### ISSUE TITLE
update to work with python 3.12

### ISSUE THREAD

**Issue by mrundle** [mrundle/mls-reddit-bot#2]
https://github.com/mrundle/mls-reddit-bot/blob/aeb9ae7e168aa5d64bfdea5b9b9c21f73c85beaa/mls_reddit_bot/reddit/__init__.py#L4

This appears to be problematic for newer versions of python currently, or at least with the version of nuitka I'm getting through homebrew. https://github.com/Nuitka/Nuitka/issues/2369

```
AttributeError: 'FileFinder' object has no attribute 'find_module'
```
